### ISSUE TITLE
Create only one table for all player

### ISSUE THREAD

**Issue by detobel36** [pseudosu/SupremeHome#2]
Why did you create one table per player !

https://github.com/pseudosu/SupremeHome/blob/master/src/main/java/me/walrus/supremehomes/network/DatabaseManager.java#L41

SQL is not design to have a lot of table. The goal is to have "a lot of" line. Not a lot of table...

**Comment by pseudosu** [comment]
As far as I know, SQL can handle multiple tables perfectly fine. Still, I do see where you're coming from. I'm going to convert the system over to one table instead. Not sure why I did it this way when I created it.

**Comment by detobel36** [comment]
> As far as I know, SQL can handle a lot tables perfectly fine.

Yes but it's not design for that...

**Comment by pseudosu** [comment]
Done  https://github.com/pseudosu/SupremeHome/commit/04d158aa7d35157e118e0723824d3ff235724762
